services:
  - type: web
    name: serenity-qr-menu
    env: static
    buildCommand: ""
    staticPublishPath: .
    plan: free
    autoDeploy: true
    domains:
      - serenity.vonbase.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html