services:
  - type: web
    name: serenity-email-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python serenity_production_ready.py
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
  - type: web  
    name: serenity-qr-menu
    env: static
    buildCommand: ""
    staticPublishPath: .
    plan: free
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html